name: Testing GPT Code Critic

on:
  push:
    branches: [main]

jobs:
  analyze-code:
    name: Test action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run GPT Code Critic
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python3 main.py

      - name: Check if results.sarif exists
        run: |
          if [ ! -f results.sarif ]; then
            echo "::error::results.sarif not found"
            exit 1
          fi

      - name: Print results
        run: |
          cat results.sarif

      - name: Upload results
        # uses: github/codeql-action/upload-sarif@v2
        uses: actions/upload-artifact@v3
        with:
          sarif_file: results.sarif
